### ISSUE TITLE
Unable to train! Missing files

### ISSUE THREAD

**Issue by nik1806** [wangy12/stereo_matching#2]
Hello @wangy12 ,

I am trying to run the code. I have followed the readme and try training with the command given on Algolux's repository (https://github.com/fjulca-aguilar/dl_stereo_matching).

python train.py --util_root=PATH_BINARY \

--data_root=PATH_DATABASE
--net_type=win19_dep9
--patch_size=19
--model_dir=MODEL_DIR
--phase=train &

But I received the following error.
Traceback (most recent call last):
File "train.py", line 40, in
disp_range=FLAGS.disp_range)
File "/home/docker/stereo_matching/data_handler.py", line 28, in init
self.file_ids = np.fromfile(os.path.join(util_root, 'myPerm.bin'), '<f4')
FileNotFoundError: [Errno 2] No such file or directory: 'PATH_BINARY/myPerm.bin'
^C
[1]+ Exit 1

Could you please help solve the issue?
Thanks!

**Comment by wangy12** [comment]
Sorry to tell everyone but I currently won't maintain this repo anymore
